### PR TITLE
Update elf dependency to v0.6.0

### PR DESCRIPTION
**Pull request by cole14**
Here's a version of #196 that applies the interface changes found in v0.6.0 :)

Note - I added some nice fuzz testing and fixed a few discovered bugs in v0.6.0

### CODE REVIEW

**Comment by cole14** [comment]
@microsoft-github-policy-service agree

**Comment by cole14** [comment]
Updated the PR after running cargo fmt :)

**Comment by cole14** [comment]
Hmm, not sure if my force push to update the branch messed up the github actions workflow. I can close/open a new PR with the updated commit if that helps

**Comment by bmc-msft** [comment]
@cole14, This isn't an issue I've seen in the past.  Of note, the microsoft-github-policy-service message disappeared, as well as the resulting license/cla confirmation, both of which is unusual.

Could you close & reopen this PR?  If that doesn't work, I'll integrate the changes from your fork instead.

**Comment by cole14** [comment]
Yup can do

**Pull request closed without merging**
